// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk7DStjvraWg6x0WcH5GfGIIcAJqSY-HQ',
    appId: '1:225062424271:web:30bf2c91a06673bcddf1ba',
    messagingSenderId: '225062424271',
    projectId: 'attendly-project',
    authDomain: 'attendly-project.firebaseapp.com',
    storageBucket: 'attendly-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE8BO7gOuKD-bsgSnSlfJ9LbtM5rhPjes',
    appId: '1:225062424271:android:642a15abb71f1078ddf1ba',
    messagingSenderId: '225062424271',
    projectId: 'attendly-project',
    storageBucket: 'attendly-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-zyFNZpid5NJaSgtH-7kPKPEsn9pHL1A',
    appId: '1:225062424271:ios:57637e89046782baddf1ba',
    messagingSenderId: '225062424271',
    projectId: 'attendly-project',
    storageBucket: 'attendly-project.firebasestorage.app',
    iosBundleId: 'com.example.professor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-zyFNZpid5NJaSgtH-7kPKPEsn9pHL1A',
    appId: '1:225062424271:ios:57637e89046782baddf1ba',
    messagingSenderId: '225062424271',
    projectId: 'attendly-project',
    storageBucket: 'attendly-project.firebasestorage.app',
    iosBundleId: 'com.example.professor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk7DStjvraWg6x0WcH5GfGIIcAJqSY-HQ',
    appId: '1:225062424271:web:0a607b1b0154c068ddf1ba',
    messagingSenderId: '225062424271',
    projectId: 'attendly-project',
    authDomain: 'attendly-project.firebaseapp.com',
    storageBucket: 'attendly-project.firebasestorage.app',
  );

}